### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by gklezd** [uwseds-sp18/homework-3-reyadji#1]
Issues:

- You copied your code from hw2 together with the bug I mentioned back then. Fix it.

**Comment by reyadji** [comment]
I just double checked, and it does have the fix for the bug in HW2.
`self.assertTrue(
set(self.test_df.columns) == set(['category_id', 'video_id', 'language']))`

Are you sure you have the latest commit?

**Comment by gklezd** [comment]
I am talking about the following line:

df_fr = df_us.assign(language='fr')

where you assign the us videos to the french video dataframe. No points are taken off for this but still fix it.
